Repository Calinou/scoop-games, pull requests merged in 2019-12, with the labels that each got.

#74 Citra(-canary): add persistence
  bucket/citra-canary.json
  bucket/citra.json
Labels: enhancement

#72 Add mGBA
  bucket/mgba-dev.json
  bucket/mgba.json
Labels: new package

#76 Add persist for BGB, Kega-Fusion, Snes9x packages
  bucket/bgb.json
  bucket/kega-fusion.json
  bucket/snes9x.json
Labels: bug

#77 mgba-dev: fix hash + clean versioning
  bucket/mgba-dev.json
Labels: bug

#79 dolphin-dev: Fix autoupdate
  bucket/dolphin-dev.json
Labels: bug

#80 mesen: Add version 0.9.8
  bucket/mesen.json
Labels: new package

#73 Warzone2100 installation fixed
  bucket/warzone2100.json
Labels: bug, enhancement

#81 MAME: Add version 0.217
  bucket/mame.json
Labels: new package

#82 Enigma: Add version 1.21
  bucket/enigma.json
Labels: new package
