Repository Calinou/scoop-games, pull requests merged in 2020-02, with the labels that each got.

#83 OpenRA: Update to version 20191117 (manually)
  bucket/openra.json
Labels: package update

#86 gzdoom, lzdoom: Update manually
  bucket/gzdoom.json
  bucket/lzdoom.json
Labels: package update

#85 nethack: Update to version 3.6.4 (manually)
  bucket/nethack.json
Labels: package update

#84 sw-exporter: Update to version 0.0.31 (manually)
  bucket/sw-exporter.json
Labels: package update

#88 rpcs3-dev: new package
  bucket/rpcs3-dev.json
Labels: new package

#89 rpcs3-dev: fix autoupdate
  bucket/rpcs3-dev.json
Labels: bug

#90 vortex: add version 1.1.14
  bucket/vortex.json
Labels: new package
