Repository Calinou/scoop-games, pull requests merged in 2020-12, with the labels that each got.

#170 sauerbraten: Update to version 2020-edition
  bucket/sauerbraten.json
Labels: package update

#171 redeclipse: Update to version 2.0.0
  bucket/redeclipse.json
Labels: package update

#173 mcrcon: Add version 0.7.1
  bucket/mcrcon.json
Labels: new package

#172 minecraft: Fix launch error
  bucket/minecraft.json
Labels: bug

#177 undertale-mod-tool: Update to version 0.3.5.4
  bucket/undertale-mod-tool.json
Labels: package update

#178 katrain: Add version 1.7
  bucket/katrain.json
Labels: new package

#180 loot: Update to version 0.16.0
  bucket/loot.json
Labels: package update

#176 amulet-map-editor: Add version 0.7.2.8
  bucket/amulet-map-editor.json
Labels: new package
