Repository Calinou/scoop-games, pull requests merged in 2020-07, with the labels that each got.

#132 Add Undertale Mod Tool version 0.3.0-4
  bucket/undertale-mod-tool.json
Labels: new package

#133 undertale-mod-tool: Update to version 0.3.0-6
  bucket/undertale-mod-tool.json
Labels: package update

#134 minetest: Make the screenshots directory persistent
  bucket/minetest.json
Labels: enhancement
