Repository Calinou/scoop-games, pull requests merged in 2020-04, with the labels that each got.

#102 Fix version number for openttd
  bucket/openttd.json
Labels: bug

#105 warzone2100: fix url
  bucket/warzone2100.json
Labels: bug

#106 gzdoom: Persist config file
  bucket/gzdoom.json
Labels: enhancement

#107 zdl: Add version 3-1.1
  bucket/zdl.json
Labels: new package

#108 ps3-system-software: Add version 4.86
  bucket/ps3-system-software.json
  bucket/rpcs3-dev.json
Labels: new package
