Repository Calinou/scoop-games, pull requests merged in 2020-05, with the labels that each got.

#109 multimc-dev: Add autoupdate
  bucket/multimc-dev.json
Labels: enhancement

#110 vortex: Update to version 1.2.10
  bucket/vortex.json
Labels: package update

#104 Fix various homepage URLs
  bucket/minecraft.json
  bucket/runebook.json
  bucket/trenchbroom.json
  bucket/xmoto.json
Labels: bug

#111 warsow: Update download URL as the previous one is down
  bucket/warsow.json
Labels: bug

#112 vkquake: Add version 1.04.1
  bucket/vkquake.json
Labels: new package

#113 openmw-nightly: Fix URLs and checkver following migration
  bucket/openmw-nightly.json
Labels: bug

#114 rpcs3-dev: Allow for multiple digits in version
  bucket/rpcs3-dev.json
Labels: bug

#115 pcsx2, pcsx2-dev: Update to version 1.6.0
  bucket/pcsx2-dev.json
  bucket/pcsx2.json
Labels: package update

#123 openmw-nightly: Change versioning scheme
  bucket/openmw-nightly.json
Labels: bug

#119 eduke32: Implement various manifest improvements
  bucket/eduke32.json
Labels: bug, enhancement

#121 vkquake: Implement various manifest improvements
  bucket/vkquake.json
Labels: bug, enhancement

#120 quakespasm: Implement various manifest improvements
  bucket/quakespasm.json
Labels: bug, enhancement

#116 actools: Add version 0.8.2123.36398
  bucket/actools.json
Labels: new package
