Repository Calinou/scoop-games, pull requests merged in 2020-06, with the labels that each got.

#122 minecraft: Add autoupdate
  bucket/minecraft.json
Labels: enhancement

#127 openra: Update to version 20200503
  bucket/openra.json
Labels: package update

#129 pathofbuilding-community: Add version 1.4.169.1
  bucket/pathofbuilding-community.json
Labels: new package
