Repository Calinou/scoop-games, pull requests merged in 2021-03, with the labels that each got.

#212 openmw-nightly: Fix archive name
  bucket/openmw-nightly.json
Labels: bug

#214 katrain: Fix autoupdate
  bucket/katrain.json
Labels: bug, package update

#215 doom-retro: Add 4.0.4
  bucket/doom-retro.json
Labels: new package

#220 doom-retro: fix notes
  bucket/doom-retro.json
Labels: bug

#219 tooniversal: Add version 1.1.0
  bucket/tooniversal.json
Labels: new package

#217 toontownrewritten: Add version 1.2.5
  bucket/toontownrewritten.json
Labels: new package

#224 toontownrewritten: Fix trailing whitespaces
  bucket/toontownrewritten.json
Labels: bug

#218 corporateclash: Add version 1.2.0
  bucket/corporateclash.json
Labels: new package

#223 jim: Add version 0.9.9.9.7
  bucket/jim.json
Labels: new package

#226 advanced-genie-editor: Add version 2021.3.15
  bucket/advanced-genie-editor.json
Labels: new package

#227 Add r2modman version 3.1.9
  bucket/r2modman.json
Labels: new package
