Repository Calinou/scoop-games, pull requests merged in 2021-11, with the labels that each got.

#464 openmw: Update to version 0.47.0
  bucket/openmw.json
Labels: package update

#465 ps3-system-software: Fix autoupdate
  bucket/ps3-system-software.json
Labels: bug

#485 pcsx2-dev: fix checkver regex and autoupdate url
  bucket/pcsx2-dev.json
Labels: bug

#486 rbxfpsunlocker: Add version 4.4.0
  bucket/rbxfpsunlocker.json
Labels: new package
