Repository Calinou/scoop-games, pull requests merged in 2021-07, with the labels that each got.

#275 mcedit2: Fix autoupdate
  bucket/mcedit2.json
Labels: bug

#265 yuzu: Add version 0-661
  bucket/yuzu.json
Labels: new package

#277 toontownoffline: Add persists
  bucket/toontownoffline.json
Labels: enhancement

#276 toontownrewritten: Add persists
  bucket/toontownrewritten.json
Labels: enhancement

#278 tooniversal: Add persists
  bucket/tooniversal.json
Labels: enhancement

#280 cemu: Add version 1.23.1b
  bucket/cemu.json
Labels: new package

#289 mednaffe: script fix
  bucket/mednaffe.json
Labels: bug

#283 project64: Add version 3.0.1
  bucket/project64.json
Labels: new package

#286 project64-dev: Add 3.0.1-5654-958b700
  bucket/project64-dev.json
Labels: new package

#279 golly: Add version 4.0
  bucket/golly.json
Labels: new package

#282 cemuhook: Add version 0.5.7.3
  bucket/cemuhook.json
Labels: new package

#287 opdessertstorm: Add version 1.0.0
  bucket/opdessertstorm.json
Labels: new package

#285 mesen-s: Add version 0.4.0
  mesen-s.json
Labels: new package

#291 mgba-dev: Fix for #290
  bucket/mgba-dev.json
Labels: bug

#294 Fix "invalid JSON primitive" error
  bucket/mgba-dev.json
Labels: bug

#296 project64: Fix hash
  bucket/project64.json
Labels: bug
