Repository Calinou/scoop-games, pull requests merged in 2021-08, with the labels that each got.

#298 openmw-nightly: Fix checkver regex
  bucket/openmw-nightly.json
Labels: bug

#301 powdertoy: Fix installation, add 64-bit version
  bucket/powdertoy.json
Labels: bug, enhancement

#304 pacmc: Update GitHub links
  bucket/pacmc.json
Labels: enhancement
