Repository Calinou/scoop-games, pull requests merged in 2021-02, with the labels that each got.

#187 undertale-mod-tool: manifest cleanup and added persist conf file
  bucket/undertale-mod-tool.json
Labels: enhancement

#188 openmw-nightly: Fix manifest for new build system
  bucket/openmw-nightly.json
Labels: bug, package update

#189 cxbx-reloaded: Add version 0.2021.0202.1246
  bucket/cxbx-reloaded.json
Labels: new package

#190 openmw-nightly: Fix for Windows PowerShell
  bucket/openmw-nightly.json
Labels: bug

#193 Ryujinx: Add 1.0.6551
  bucket/ryujinx-dev.json
Labels: new package

#191 BetterJoy: Add v6.4b
  bucket/betterjoy.json
Labels: new package

#192 Duckstation: Add nightly
  bucket/duckstation.json
Labels: new package

#194 triplea: Add 2.5.22294
  bucket/triplea.json
Labels: new package

#203 powdertoy: Add 95.0
  bucket/powdertoy.json
Labels: new package

#206 mgba-dev: return to normal versioning
  bucket/mgba-dev.json
Labels: enhancement

#207 Make various improvements to manifests
  bucket/dolphin-dev.json
  bucket/dolphin.json
  bucket/melonds.json
  bucket/pcsx2-dev.json
  bucket/pcsx2.json
  bucket/ryujinx-dev.json
  bucket/xenia.json
Labels: enhancement
