Repository Calinou/scoop-games, pull requests merged in 2021-06, with the labels that each got.

#263 openmw-nightly: Fix autoupdate
  bucket/openmw-nightly.json
Labels: bug

#250 dolphin: Fix portable mode broken by c63f4af
  bucket/dolphin-dev.json
  bucket/dolphin.json
Labels: bug

#264 openmw-nightly: Update only if the build passed
  bucket/openmw-nightly.json
Labels: bug

#103 Add mednafen(-dev) and mednaffe manifests
  bucket/mednafen-dev.json
  bucket/mednafen.json
  bucket/mednaffe.json
Labels: new package

#267 xenia: fix persistence
  bucket/xenia.json
Labels: bug

#268 yquake2: Update to version 8.00
  bucket/yquake2.json
Labels: package update

#269 mame: Overhaul
  bucket/mame.json
Labels: bug, enhancement, package update

#272 pacmc: Add version 0.1.1
  bucket/pacmc.json
Labels: new package

#261 toontownfellowship: Add version 1.0.0
  bucket/toontownfellowship.json
Labels: new package

#262 toontownoffline: Add version 1.0.0
  bucket/toontownoffline.json
Labels: new package

#273 pacmc: Improve license name, fix extract_dir
  bucket/pacmc.json
Labels: bug, enhancement, package update
