Repository Calinou/scoop-games, pull requests merged in 2021-04, with the labels that each got.

#230 ryujinx-dev: Update persistence
  bucket/ryujinx-dev.json
Labels: enhancement

#231 Update yquake2.json
  bucket/yquake2.json
Labels: enhancement, package update

#234 raze: Update to version 1.0.1
  bucket/raze.json
Labels: package update

#233 vkquake2: Add version 1.5.7
  bucket/vkquake2.json
Labels: new package

#238 tooniversal: Fix game downloading required file called tooniversal.exe
  bucket/tooniversal.json
Labels: bug

#239 vortex: Fix and update to version 1.4.10
  bucket/vortex.json
Labels: bug, package update

#243 mcservman: Add version 0.0.6
  bucket/mcservman.json
Labels: new package
