Repository Calinou/scoop-games, pull requests merged in 2021-12, with the labels that each got.

#489 mgba: Update to version 0.9.3, tweak checkver and autoupdate
  bucket/mgba.json
Labels: enhancement, package update

#491 rbxfpsunlocker: Update to version 4.4.1, fix autoupdate
  bucket/rbxfpsunlocker.json
Labels: bug, package update

#490 doom-retro: Fix config file persist and add info to notes
  bucket/doom-retro.json
Labels: bug, enhancement

#492 nanoboyadvance: Add version 1.4
  bucket/nanoboyadvance.json
Labels: new package

#488 flycast: Update to version 1.2
  bucket/flycast.json
Labels: bug, package update

#237 dgvoodoo2: Add version 2.77
  bucket/dgvoodoo2.json
Labels: new package

#494 dxwrapper: Add version 1.0.6542.21
  bucket/dxwrapper.json
Labels: new package

#496 nanoboyadvance: Fix hash
  bucket/nanoboyadvance.json
Labels: bug

#495 dxvk: Add version 1.9.2
  bucket/dxvk.json
Labels: new package

#498 rayman-control-panel: Add version 12.1.0
  bucket/rayman-control-panel.json
Labels: new package

#497 demulshooter: Add version 10.4.1
  bucket/demulshooter.json
Labels: new package
