Repository Calinou/scoop-games, pull requests merged in 2021-05, with the labels that each got.

#236 fbneo: Add version 1.0.0.2
  bucket/fbneo.json
Labels: new package

#235 mameui: Add version nightly
  bucket/mameui.json
Labels: new package

#248 mameui: Add description, persist folders
  bucket/mameui.json
Labels: enhancement

#249 hedgewars: Update to version 1.0.0
  bucket/hedgewars.json
Labels: package update

#211 dwarf-fortress: Persist the `data` folder
  bucket/dwarf-fortress.json
Labels: enhancement

#252 mcservman: Update to version 0.0.7
  bucket/mcservman.json
Labels: package update

#253 Add OpenHV version 20210321
  bucket/openhv.json
Labels: new package

#257 Improve amidst.json
  bucket/amidst.json
Labels: enhancement

#260 assetstudio: Update to version 0.15.47, add autoupdate
  bucket/assetstudio.json
Labels: enhancement, package update

#258 srb2kart: Add version 1.3
  bucket/srb2kart.json
Labels: new package
