Repository Calinou/scoop-games, pull requests merged in 2021-09, with the labels that each got.

#305 melonds: Update to version 0.9.3, fix autoupdate
  bucket/melonds.json
Labels: package update

#308 duckstation: add auto updater
  bucket/duckstation.json
Labels: enhancement

#310 Add RPCS3 persist files and folders.
  bucket/rpcs3-dev.json
Labels: enhancement

#312 opdessertstorm: Remove trailing whitespace
  bucket/opdessertstorm.json
Labels: bug

#311 rpcs3-dev: Create `.yml` files if they don't exist
  bucket/rpcs3-dev.json
Labels: bug

#314 osulazer: Fix `extract_dir`
  bucket/osulazer.json
Labels: bug

#316 fbneo: Fix autoupdate
  bucket/fbneo.json
Labels: bug

#317 flycast: Add version 1.1
  bucket/flycast.json
Labels: new package

#319 pcsx2-dev: Fix autoupdate commit regex
  bucket/pcsx2-dev.json
Labels: bug
