Repository Calinou/scoop-games, pull requests merged in 2022-01, with the labels that each got.

#507 toontownrewritten: Update to version 1.3.2
  bucket/toontownrewritten.json
Labels: package update

#509 toontownoffline: Fix download for 1.0.0
  bucket/toontownoffline.json
Labels: bug

#450 m64p: Add version 2021.10.28
  bucket/m64p.json
Labels: new package

#455 ares: Add version 124
  bucket/ares.json
Labels: new package

#456 xebra: Add version 211031
  bucket/xebra.json
Labels: new package

#514 xenia: Update download location for 1.0.2555
  bucket/xenia.json
Labels: bug

#515 ryujinx-dev: Update to version 1.1.9
  bucket/ryujinx-dev.json
Labels: bug, package update

#516 scummvm: Add version 2.5.1
  bucket/scummvm.json
Labels: new package

#520 xenia: Fix persist list
  bucket/xenia.json
Labels: bug

#521 Remove MCServMan project (deleted and discontinued)
  bucket/mcservman.json
Labels: bug

#519 doom-retro: Improve the Notes section
  bucket/doom-retro.json
Labels: enhancement
