Repository Calinou/scoop-games, pull requests merged in 2022-10, with the labels that each got.

#706 opensupaplex: Add version 7.1.2
  bucket/opensupaplex.json
Labels: new package

#707 rimpy-pre-release: Add version 1.2.6.25
  bucket/rimpy-pre-release.json
Labels: new package, review-needed

#708 heroic-games-launcher: Add version 2.4.3
  bucket/heroic-games-launcher.json
Labels: new package, review-needed

#710 clonehero: Add version 0.23.2.2
  bucket/clonehero.json
Labels: new package

#711 pegasus: Add version alpha16-42-g996720eb
  bucket/pegasus.json
Labels: new package, review-needed

#712 pegasus: Fix notes, add `pre_install`
  bucket/pegasus.json
Labels: review-needed

#695 rimpy: Add 1.2.5.21
  bucket/rimpy.json
Labels: new package

#723 prismlauncher, prismlauncher-qt5: Add version 5.0
  bucket/prismlauncher-qt5.json
  bucket/prismlauncher.json
Labels: new package

#732 amulet-map-editor: Fix version and website URL
  bucket/amulet-map-editor.json
Labels: bug
