Repository Calinou/scoop-games, pull requests merged in 2022-09, with the labels that each got.

#689 m64p: Rename to simple64
  bucket/m64p.json
  bucket/simple64.json
Labels: bug

#697 cnc-ddraw@4.4.9.0: Fix hash
  bucket/cnc-ddraw.json
Labels: bug

#699 xonotic: Update to version 0.8.5
  bucket/xonotic.json
Labels: package update

#691 bsnes-mt: Add version 1.3.4
  bucket/bsnes-mt.json
Labels: new package, review-needed

#700 Cemu: Update and change release source
  bucket/cemu-dev.json
  bucket/cemu.json
Labels: review-needed

#702 cemuhook: Remove as it's deprecated since Cemu 2.0
  bucket/cemuhook.json
Labels: package removal

#704 tf2-hud-editor: Add version 2.5
  bucket/tf2-hud-editor.json
Labels: new package, review-needed
