Repository Calinou/scoop-games, pull requests merged in 2022-06, with the labels that each got.

#634 Update Tickompiler to v1.10.0-hotfix
  bucket/tickompiler.json
Labels: package update

#636 Fix ares update
  bucket/ares.json
Labels: bug

#640 openmw-nightly: Fix checkver
  bucket/openmw-nightly.json
Labels: bug

#641 openmw-nightly: Fix install
  bucket/openmw-nightly.json
Labels: bug

#643 cemu: Fix persist
  bucket/cemu.json
Labels: bug

#646 livesplit: Add version 1.8.19
  bucket/livesplit.json
Labels: new package

#648 vkquake: Persist for the Arcane Dimensions mod
  bucket/vkquake.json
Labels: enhancement, review-needed
