Repository Calinou/scoop-games, pull requests merged in 2022-02, with the labels that each got.

#522 doom-retro@4.4.4: Fix hash
  bucket/doom-retro.json
Labels: bug

#527 openmw-nightly: Fix checkver
  bucket/openmw-nightly.json
Labels: bug

#526 xenia-canary: Add version 7b6cbc2
  bucket/xenia-canary.json
Labels: new package

#528 mga: Fix checkver
  bucket/mgba.json
Labels: bug

#529 xemu: Add version 0.6.2-75-g8919bae311
  bucket/xemu.json
Labels: new package

#533 vita3k-dev: Add version 764b98
  bucket/vita3k-dev.json
Labels: new package

#532 retroarch: Add version 1.10.0
  bucket/retroarch.json
Labels: new package

#537 Fix various things in Redream, Xenia and Yuzu manifests
  bucket/redream-nightly.json
  bucket/redream.json
  bucket/xenia-canary.json
  bucket/xenia.json
  bucket/yuzu-pineapple.json
  bucket/yuzu.json
Labels: bug

#538 rpcs3-dev: Persist more files
  bucket/rpcs3-dev.json
Labels: enhancement

#540 cemu: Fix hash, add description
  bucket/cemu.json
Labels: bug, enhancement

#539 rpcs3: Suggest vcredist2019 instead of depending on it
  bucket/rpcs3-dev.json
Labels: enhancement

#535 retroarch-nightly: Add version nightly
  bucket/retroarch-nightly.json
Labels: new package

#543 rpcs3: Remove duplicate persists
  bucket/rpcs3-dev.json
Labels: bug

#550 ppsspp-dev: Fix download link to be downloaded as 7z file
  bucket/ppsspp-dev.json
Labels: bug

#544 cemu: Add shaderCache to persists
  bucket/cemu.json
Labels: enhancement

#542 Fix preinstall for xenia and xenia-canary
  bucket/xenia-canary.json
  bucket/xenia.json
Labels: bug

#482 vkquake2: Add persist
  bucket/vkquake2.json
Labels: enhancement

#480 q2pro: Add 64-bit and persist, use versioned release
  bucket/q2pro.json
Labels: enhancement

#475 blade-of-agony: Update to version 3.1, use ModDB download, add persist
  bucket/blade-of-agony.json
Labels: enhancement

#473 freeorion: Add fullscreen shortcut, remove broken `bin`
  bucket/freeorion.json
Labels: bug, enhancement

#472 spearmint: Add persist, add OpenArena mission pack shortcut, improve notes
  bucket/spearmint.json
Labels: enhancement

#469 freedoom: Update to version 0.12.1, add shortcut to manual, add notes
  bucket/freedoom.json
Labels: enhancement, package update

#409 neverball: Add autoupdate
  bucket/neverball.json
Labels: enhancement

#370 augmentinel: Update to version 1.5, add autoupdate, install from ZIP
  bucket/augmentinel.json
Labels: enhancement, package update

#556 yuzu, yuzu-pineapple: Fix install location
  bucket/yuzu-pineapple.json
  bucket/yuzu.json
Labels: bug

#531 ppsspp: Add version 1.12.3
  bucket/ppsspp.json
Labels: new package

#562 yuzu: Update license
  bucket/yuzu-pineapple.json
  bucket/yuzu.json
Labels: bug

#552 multimc: Update to version 0.6.14
  bucket/multimc.json
Labels: bug, package update

#565 polymc: Add version 1.0.6
  bucket/polymc.json
Labels: new package

#566 advanced-genie-editor: Remove as it's broken
  bucket/advanced-genie-editor.json
Labels: bug

#567 brogue: Remove as it's broken
  bucket/brogue.json
Labels: bug

#569 ioquake3: Remove as it's broken
  bucket/ioquake3.json
Labels: bug

#570 blitz: Remove as it's outdated and broken
  bucket/blitz.json
Labels: bug

#571 openra: Fix checkver
  bucket/openra.json
Labels: bug
