Repository Calinou/scoop-games, pull requests merged in 2022-04, with the labels that each got.

#604 pcsx2-dev: Remove 32-bit builds
  bucket/pcsx2-dev.json
Labels: bug

#607 unrealmodloader: Add version 2.2.0
  bucket/unrealmodloader.json
Labels: new package

#608 sameboy: Add version 0.14.7
  bucket/sameboy.json
Labels: new package

#609 unrealmodloader: Add note for autoinjector tool
  bucket/unrealmodloader.json
Labels: enhancement

#613 demulshooter: Update to version 10.5.0
  bucket/demulshooter.json
Labels: package update
