Repository Calinou/scoop-games, pull requests merged in 2022-08, with the labels that each got.

#670 ares: Fix autoupdate
  bucket/ares.json
Labels: bug

#669 jazz2-resurrection: Add version 0.7.3
  bucket/jazz2-resurrection.json
Labels: new package, review-needed

#671 romsorter: Add Release 5
  bucket/romsorter.json
Labels: new package, review-needed

#672 jazz2-resurrection: Fix grammar in Notes
  bucket/jazz2-resurrection.json
Labels: bug

#673 polymc: Use portable version instead
  bucket/polymc.json
Labels: enhancement

#674 Revert "polymc: Use portable version instead (#673)"
  bucket/polymc.json
Labels: bug

#676 vita3k: Update to version 2786-7ac13c3
  bucket/vita3k.json
Labels: enhancement, package update

#678 vita3k: Remove `lang`, `shaders-builtin`, `data` persist
  bucket/vita3k.json
Labels: bug, review-needed

#679 itch: Add version 25.5.1
  bucket/itch.json
Labels: new package

#680 gzdoom: Make Save and Screenshots persistent
  bucket/gzdoom.json
Labels: enhancement

#686 Simplify PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: enhancement
