Repository Calinou/scoop-games, pull requests merged in 2022-12, with the labels that each got.

#757 vkquake: Remove `extract_dir` to fix installation
  bucket/vkquake.json
Labels: bug, review-needed

#759 duckstation-preview: Add version 20221208-g1905ce3
  bucket/duckstation-preview.json
Labels: new package, review-needed

#761 doom-retro@4.7: Fix hash
  bucket/doom-retro.json
Labels: bug

#753 rare: Add version 1.9.4
  bucket/rare.json
Labels: review-needed

#762 prismlauncher/prismlauncher-qt5: Update to v6.0, add associations
  bucket/prismlauncher-qt5.json
  bucket/prismlauncher.json
  scripts/prismlauncher-qt5/install-associations.reg
  scripts/prismlauncher-qt5/uninstall-associations.reg
  scripts/prismlauncher/install-associations.reg
  scripts/prismlauncher/uninstall-associations.reg
Labels: enhancement, package update

#764 pegasus: Fix `checkver` to be more reliable for version checking
  bucket/pegasus.json
Labels: bug, review-needed

#766 steam-achievement-manager: Add version 7.0.25
  bucket/steam-achievement-manager.json
Labels: new package, review-needed

#765 wfinfo: Add version 9.5.6
  bucket/wfinfo.json
Labels: new package, review-needed

#768 zandronum: Update to 3.1
  bucket/zandronum.json
Labels: package update, review-needed

#770 zandronum: Add suggested fixes
  bucket/zandronum.json
Labels: bug, review-needed

#769 cambridge: Add version 0.3
  bucket/cambridge.json
Labels: new package, review-needed

#745 ppsspp(-dev): Fix manifests, Update `test.ps1` to Pester 5
  bin/test.ps1
  bucket/ppsspp-dev.json
  bucket/ppsspp.json
Labels: review-needed

#774 toontownrewritten: Update to version 1.5.2.0
  bucket/toontownrewritten.json
Labels: package update

#715 unciv: Add version 4.2.12
  bucket/unciv.json
Labels: review-needed

#776 ares: Update to version 131, add ARM64 architecture
  bucket/ares.json
Labels: enhancement, package update, review-needed
