Repository Calinou/scoop-games, pull requests merged in 2022-05, with the labels that each got.

#616 ferium: Add version 3.27.0
  bucket/ferium.json
Labels: new package

#619 sixcells: Add version 2.4.3
  bucket/sixcells.json
Labels: new package, review-needed

#618 l4d2modmanager: Add version 1.0.4
  bucket/l4d2modmanager.json
Labels: new package, review-needed

#621 spraygen: Add version 1.3.4
  bucket/spraygen.json
Labels: review-needed

#620 l4d2modmanager: Fix persist with a pre_install script
  bucket/l4d2modmanager.json
Labels: bug, review-needed

#624 mame: Update to version 0.243, fix autoupdate
  bucket/mame.json
Labels: bug, package update

#622 pacmc: Update license and description
  bucket/pacmc.json
Labels: enhancement

#625 rpcs3: Fix `config.yml` and `games.yml` not persisting between upgrades
  bucket/rpcs3.json
Labels: bug

#627 pcsx2-dev: Fix download URL for Qt release
  bucket/pcsx2-dev.json
Labels: bug

#628 ferium: Update to version 4.0.2, improve description
  bucket/ferium.json
Labels: enhancement, package update

#629 ferium: Fix version 4.0.2, update URLs
  bucket/ferium.json
Labels: bug

#630 melonds: Update to 0.9.4
  bucket/melonds.json
Labels: package update

#632 pcsx2-dev: Disable built-in autoupdate to prevent conflicts
  bucket/pcsx2-dev.json
Labels: bug

#633 rpcs3: Fix persistence and disable built-in autoupdate
  bucket/rpcs3.json
Labels: bug
