Repository Calinou/scoop-games, pull requests merged in 2022-07, with the labels that each got.

#651 yquake2-ref-vk: Add version 1.0.2
  bucket/yquake2-ref-vk.json
Labels: review-needed

#650 raine: Add version 0.93.5d
  bucket/raine.json
Labels: review-needed

#653 raine: Use HTTPS for autoupdate
  bucket/raine.json
Labels: enhancement, review-needed

#655 ironwail: Add version 0.6.0
  bucket/ironwail.json
Labels: review-needed

#652 yquake2: Add suggestion for yquake2-ref-vk
  bucket/yquake2.json
Labels: review-needed

#658 game-backup-monitor: Add version 1.3.1
  bucket/game-backup-monitor.json
Labels: new package

#656 kindandfair: Add version 1.5.2
  bucket/kindandfair.json
Labels: review-needed

#661 polymc: Update to 1.4.0, add polymc-qt5
  bucket/polymc-qt5.json
  bucket/polymc.json
Labels: package update

#663 ferium: simplify autoupdate hash
  bucket/ferium.json
Labels: enhancement

#665 cnc-ddraw: Add version 4.4.7.0
  bucket/cnc-ddraw.json
Labels: new package, review-needed

#666 ironwail: Add info about automatic detection of the Steam release
  bucket/ironwail.json
Labels: enhancement

#667 doomrunner: Add version 1.5.1
  bucket/doomrunner.json
Labels: new package, review-needed
