Repository Calinou/scoop-games, pull requests merged in 2022-03, with the labels that each got.

#551 ci: Automatically try to update packages
  .github/workflows/excavator.yml
Labels: enhancement

#576 polymc: Fix hash
  bucket/polymc.json
Labels: bug

#577 ares: Fix autoupdate and extract_dir
  bucket/ares.json
Labels: bug

#578 bin: Fix formatjson and others erroring
  Scoop-Bucket.Tests.ps1
  bin/auto-pr.ps1
  bin/checkurls.ps1
  bin/checkver.ps1
  bin/formatjson.ps1
  bin/missing-checkver.ps1
  bin/test.ps1
Labels: bug

#581 Fix and improve various manifests
  bucket/betterjoy.json
  bucket/cemu.json
  bucket/citra-canary.json
  bucket/citra.json
  bucket/dolphin-beta.json
  bucket/dolphin-dev.json
  bucket/dolphin.json
  bucket/duckstation.json
  bucket/flycast.json
  bucket/m64p.json
  bucket/mame.json
  bucket/mednafen-dev.json
  bucket/mednafen.json
  bucket/mesen-s.json
  bucket/mesen.json
  bucket/opdessertstorm.json
  bucket/osulazer.json
  bucket/pcsx2-dev.json
  bucket/pcsx2.json
  bucket/ppsspp-dev.json
  bucket/ppsspp.json
  bucket/project64-dev.json
  bucket/project64.json
  bucket/ps3-system-software.json
  bucket/redream-dev.json
  bucket/retroarch-nightly.json
  bucket/retroarch.json
  bucket/rpcs3-dev.json
  bucket/rpcs3.json
  bucket/ryujinx.json
  bucket/scummvm.json
  bucket/snes9x-dev.json
  bucket/snes9x.json
  bucket/tooniversal.json
  bucket/toontownoffline.json
  bucket/toontownrewritten.json
  bucket/vita3k.json
  bucket/xemu.json
  bucket/xenia-canary.json
  bucket/xenia.json
  bucket/yuzu-pineapple.json
  bucket/yuzu.json
Labels: bug, enhancement

#583 bsnes: Add version 115
  bucket/bsnes.json
Labels: new package

#585 Update copyright statements to 2022
  README.md
Labels: enhancement

#586 fbneo-nightly: Add the nightly version
  bucket/fbneo-nightly.json
Labels: new package

#584 fbneo: Adjust the manifest order and Notes
  bucket/fbneo.json
Labels: enhancement

#559 newer-tanooki: Add version 1.0
  bucket/newer-tanooki.json
Labels: new package

#553 reggie-next: Add version 4.7.0
  bucket/reggie-next.json
Labels: new package

#591 wiiscrubber: Add version 1.4
  bucket/wiiscrubber.json
Labels: new package

#593 prboom-plus: Add `extract_dir`
  bucket/prboom-plus.json
Labels: bug

#594 polymc: Fix autoupdate
  bucket/polymc.json
Labels: bug, package update

#598 cemu: Fix persist of `settings.xml`
  bucket/cemu.json
Labels: bug

#601 PolyMC: Update to version 1.1.1, fix autoupdate, remove useless `persist`
  bucket/polymc.json
Labels: bug, package update

#602 polymc: Fix trailing whitespace in manifest
  bucket/polymc.json
Labels: bug

#603 PolyMC: Add multiarch
  bucket/polymc.json
Labels: enhancement
