Repository Calinou/scoop-games, pull requests merged in 2022-11, with the labels that each got.

#734 prismlauncher: Declare architecture
  bucket/prismlauncher.json
Labels: bug

#735 epic-games-launcher: Add version 14.2.1
  bucket/epic-games-launcher.json
Labels: new package, review-needed

#743 Fix bug for yuzu-pineapple and Add support for ryujinx avalonia version #742
  bucket/ryujinx-ava.json
  bucket/yuzu-pineapple.json
Labels: bug, new package

#747 Update `actions/checkout` version
  .github/workflows/ci.yml
Labels: enhancement

#752 duckstation: Fix installation
  bucket/duckstation.json
Labels: bug

#755 ares: Update website URL
  bucket/ares.json
Labels: bug
