Repository Calinou/scoop-games, pull requests merged in 2023-01, with the labels that each got.

#778 dgvoodoo2: Add shorcut
  bucket/dgvoodoo2.json
Labels: enhancement, review-needed

#780 raine@0.94.10: Fix hashes for dependencies
  bucket/raine.json
Labels: bug

#783 epic-games-launcher: Change `pre_install` to `post_install`
  bucket/epic-games-launcher.json
Labels: bug, review-needed

#784 bloxstrap: Add version 1.6.1
  bucket/bloxstrap.json
Labels: new package, review-needed

#786 pcsx2-dev: Remove unnecessary persist entry
  bucket/pcsx2-dev.json
Labels: bug

#787 bgb: Update to version 1.5.10
  bucket/bgb.json
Labels: package update

#793 texmod, umod: Add version 2_r53
  bucket/texmod.json
  bucket/umod.json
Labels: new package, manifest-fix-needed

#795 ppsspp(-dev): Remove extract_dir, bin, Add 32bit arch
  bucket/ppsspp-dev.json
  bucket/ppsspp.json
Labels: bug, enhancement, review-needed

#796 Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/hash-error.yml
  .github/ISSUE_TEMPLATE/package-request.yml
Labels: enhancement

#797 Rename `package-request` label to `new package` in issue template
  .github/ISSUE_TEMPLATE/package-request.yml
Labels: enhancement

#798 duelyst: Add version 1.97.12
  bucket/duelyst.json
Labels: new package

#801 racelab: Add version 3.5.0
  bucket/racelab.json
Labels: new package
