Repository Calinou/scoop-games, pull requests merged in 2023-10, with the labels that each got.

#1032 dxvk: Add extract_dir property
  bucket/dxvk.json
Labels: bug, review-needed

#1035 battlenet: Add version nightly (2.25.1.14443)
  bucket/battlenet.json
Labels: new package, review-needed

#1040 goggalaxy@2.0.72.94: Fix goggalaxy manifest
  bucket/goggalaxy.json
Labels: bug, review-needed

#1041 rbxfpsunlocker: Updated version v5.0 to v5.1
  bucket/rbxfpsunlocker.json
Labels: package update, review-needed

#1043 mudlet: Add 4.17.2
  bucket/mudlet.json
Labels: new package, review-needed

#1045 mudlet: fix JSON
  bucket/mudlet.json
Labels: bug

#1046 dgvoodoo2: Update notes
  bucket/dgvoodoo2.json
Labels: enhancement

#1047 jazz2-resurrection: Update to version 2.1.0
  bucket/jazz2-resurrection.json
Labels: enhancement, review-needed
