Repository Calinou/scoop-games, pull requests merged in 2023-05, with the labels that each got.

#886 wemod: Add version 8.6.0
  bucket/wemod.json
Labels: new package

#889 rmg; Rosalie's Mupen GUI: Add version 0.4.0
  bucket/rmg.json
Labels: new package, review-needed

#891 wemod: Update to version 8.7.0
  bucket/wemod.json
Labels: bug, package update

#892 Rare: Add version 1.10.1
  bucket/rare.json
Labels: new package, review-needed

#887 Bloxstrap: Remove 32bit version and update to 2.3.0
  bucket/bloxstrap.json
Labels: package update, review-needed

#893 rbxfpsunlocker@5.0: Add hotfix
  bucket/rbxfpsunlocker.json
Labels: package update, review-needed

#895 Add: pyfa 2.52.0
  bucket/pyfa.json
Labels: new package, review-needed

#899 Add: GOG Galaxy 2.0.62.26
  bucket/goggalaxy.json
Labels: new package, review-needed

#904 Add: steam-art-manager
  bucket/steam-art-manager.json
Labels: new package, review-needed

#760 xenia-canary: Add version 20221205172514-747fb42
  bucket/xenia-canary.json
Labels: package update, review-needed

#923 xmoto: update to 0.6.2
  bucket/xmoto.json
Labels: package update, review-needed

#924 assaultcube: update to 1.3.0.2
  bucket/assaultcube.json
Labels: package update, review-needed

#926 freeorion: update to 0.5
  bucket/freeorion.json
Labels: package update, review-needed

#929 freeorion-test: add full-screen option
  bucket/freeorion-test.json
Labels: bug, enhancement, review-needed

#928 yquake2: persist libraries and music
  bucket/yquake2.json
Labels: enhancement, review-needed

#930 undertale-mod-tool: update to 0.5.1.0 and fix shim
  bucket/undertale-mod-tool.json
Labels: bug, package update, review-needed

#932 armagetronad: update to 0.2.9.1.0 and add autoupdate
  bucket/armagetronad.json
Labels: enhancement, package update, review-needed

#934 rvgl: add hash checking and persists
  bucket/rvgl.json
Labels: enhancement, manifest-fix-needed

#938 ppsspp: update to 1.15.3 stable
  bucket/ppsspp.json
Labels: package update, review-needed

#916 simutrans: update to version 123.0.1
  bucket/simutrans.json
Labels: package update, review-needed

#898 ps3-system-software: Fix autoupdate
  bucket/ps3-system-software.json
Labels: bug, package update, review-needed

#943 goggalaxy: fix install
  bucket/goggalaxy.json
Labels: bug, review-needed

#945 stuntrally: update to 2.7
  bucket/stuntrally.json
Labels: package update

#946 enigma: update to 1.30
  bucket/enigma.json
Labels: package update, review-needed

#947 pychess: update to 1.0.4
  bucket/pychess.json
Labels: package update, review-needed

#957 ironwail: fix shim
  bucket/ironwail.json
Labels: review-needed

#953 crispy-doom: update to 6.0
  bucket/crispy-doom.json
Labels: package update, review-needed

#941 freedroidrpg: update to 1.0
  bucket/freedroidrpg.json
Labels: package update, review-needed

#950 visualboyadvance-m: update to 2.1.5
  bucket/visualboyadvance-m.json
Labels: package update, review-needed

#933 wesnoth: update to 1.16.9
  bucket/wesnoth.json
Labels: package update, review-needed

#940 nethack: update to 3.6.7 and use official site for download, add hash checking
  bucket/nethack.json
Labels: package update, review-needed

#931 bgb: persist ini and screenshot folder
  bucket/bgb.json
Labels: enhancement, review-needed

#967 wyrmsun: update to 5.3.6
  bucket/wyrmsun.json
Labels: package update, review-needed

#944 clonehero: update to 1.0.0.4080
  bucket/clonehero.json
Labels: review-needed

#969 speed-dreams: update to 2.3.0-r8786
  bucket/speed-dreams.json
Labels: package update, review-needed

#968 cataclysm-dda-tiles: update to 0.G
  bucket/cataclysm-dda-tiles.json
Labels: package update, review-needed

#937 unciv: update to 4.6.12 and remove deprecated 32 bit
  bucket/unciv.json
Labels: review-needed

#902 evemon: add version 4.2.2
  bucket/evemon.json
Labels: new package, review-needed

#920 xivlauncher: add version 6.3.4
  bucket/xivlauncher.json
Labels: new package, review-needed
