Repository Calinou/scoop-games, pull requests merged in 2023-04, with the labels that each got.

#863 doom-retro@4.9: Fix hash
  bucket/doom-retro.json
Labels: bug, review-needed

#872 uvtt2fgu: Add version 1.5.1
  bucket/uvtt2fgu.json
Labels: review-needed

#873 uvtt2fgu: Remove unused dependencies
  bucket/uvtt2fgu.json
Labels: bug, review-needed

#880 pcsx2-dev: Update to version 1.7.4436
  .vscode/settings.json
  bucket/pcsx2-dev.json
Labels: bug, package update, review-needed

#878 rvgl-launcher: Add version 0.1.22.314a1
  bucket/rvgl-launcher.json
Labels: new package, review-needed
