Repository Calinou/scoop-games, pull requests merged in 2023-03, with the labels that each got.

#833 racelab@3.7.2: Fix trailing whitespace
  bucket/racelab.json
Labels: bug

#835 tf2-hud-editor: Update to version 3.1, fix `extract_dir`
  bucket/tf2-hud-editor.json
Labels: bug, package update, review-needed

#829 raine: Update to version 0.95
  bucket/raine.json
Labels: package update, review-needed

#849 openloco: Add version 23.02
  bucket/openloco.json
Labels: new package, review-needed

#852 dgvoodoo2@2.8: Fix hash
  bucket/dgvoodoo2.json
Labels: bug

#853 melonds: Fix URL, update to 0.9.5
  bucket/melonds.json
Labels: bug, package update

#855 itch: Fix `checkver` to be more accurate
  bucket/itch.json
Labels: review-needed
