Repository Calinou/scoop-games, pull requests merged in 2023-06, with the labels that each got.

#982 modbreeze: add version 0.4.0
  bucket/modbreeze.json
Labels: new package

#897 jeveassets: add version 7.6.1
  bucket/jeveassets.json
Labels: new package, review-needed

#977 evemaptool: add version 1.20
  bucket/evemaptool.json
Labels: new package, review-needed

#992 alephone-marathon-trilogy: add version 20230529
  bucket/alephone-marathon-trilogy.json
Labels: new package, review-needed

#994 duckstation: Fix persist
  bucket/duckstation-preview.json
  bucket/duckstation.json
Labels: bug

#909 applewin: add version 1.30.14.1
  bucket/applewin.json
Labels: new package, review-needed

#906 idlemaster-extended: add version 1.10.0
  bucket/idlemaster-extended.json
Labels: new package, review-needed

#964 advanced-combat-tracker: add version 3.6.2.279
  bucket/advanced-combat-tracker.json
Labels: new package, review-needed

#965 fheroes2: Add version 1.0.4
  bucket/fheroes2.json
Labels: new package, review-needed

#997 twitchdropsminer: add version 15
  twitchdropsminer.json
Labels: new package

#981 prismlauncher/prismlauncher-qt5@7.1: start using portable binaries
  bucket/prismlauncher-qt5.json
  bucket/prismlauncher.json
Labels: enhancement, review-needed

#911 beebem: add version 4.19
  bucket/beebem.json
Labels: new package, review-needed

#959 naev: add 0.10.5
  bucket/naev.json
Labels: new package, review-needed

#1001 loot: Update to version 0.20.0
  bucket/loot.json
Labels: bug, package update, review-needed
