Repository Calinou/scoop-games, pull requests merged in 2023-02, with the labels that each got.

#806 xenia-canary: Persist `patches` folder
  bucket/xenia-canary.json
Labels: bug

#805 heroic-games-launcher: Fix `url`, remove `bin`, and fix `autoupdate`
  bucket/heroic-games-launcher.json
Labels: bug, review-needed

#809 steam-rom-manager: Add version 2.3.40
  bucket/steam-rom-manager.json
Labels: new package

#811 veloren-weekly: Add version 2023-02-01T10_41
  bucket/veloren-weekly.json
Labels: new package

#827 tf2-hud-editor: Fix `extract_dir` following upstream changes
  bucket/tf2-hud-editor.json
Labels: bug

#830 openttd: Update to version 13.0, add checkver and autoupdate
  bucket/openttd.json
Labels: enhancement

#789 runelite: Add version 2.6.1
  bucket/runelite.json
Labels: new package, review-needed

#802 crewchief: Add version 4.16.3.5
  bucket/crewchief.json
Labels: new package

#713 ludo: Add version 0.16.20
  bucket/ludo.json
Labels: new package, review-needed

#831 flycast: Update to version 2.1
  bucket/flycast.json
Labels: package update
