Repository Calinou/scoop-games, pull requests merged in 2024-02, with the labels that each got.

#1085 ADD: tmaze
  bucket/tmaze.json
Labels: new package

#1089 Add chiaki4deck
  bucket/chiaki4deck.json
Labels: new package, review-needed

#1093 syntax-tm's Steam Achievement Manager: Add version 0.2.0
  bucket/steam-achievement-manager-syntaxtm.json
Labels: new package, review-needed

#1095 scummvm: Fix installation path and ini file
  bucket/scummvm.json
Labels: bug

#1096 chore(ci): switch to `pull_request_target` trigger
  .github/workflows/pull_request.yml
Labels: enhancement
