Repository Calinou/scoop-games, pull requests merged in 2024-03, with the labels that each got.

#1099 prismlauncher: Persist catpacks and iconthemes
  bucket/prismlauncher-qt5.json
  bucket/prismlauncher.json
Labels: manifest-fix-needed

#1102 battlenet: Add shortcut
  bucket/battlenet.json
Labels: enhancement, review-needed

#1104 ps3-system-software: fix autoupdate
  bucket/ps3-system-software.json
Labels: bug, manifest-fix-needed

#1108 freeorion 0.5.0.1: Fix `url`
  bucket/freeorion.json
Labels: bug, review-needed

#1113 Sudachi: add version v7715077
  bucket/sudachi.json
Labels: new package, review-needed

#1117 Update PathOfBuilding-Community to v2.40.1 & fix autoupdate
  bucket/pathofbuilding-community.json
Labels: bug, package update, review-needed

#1109 demulshooter: Update to version 12
  bucket/demulshooter.json
Labels: package update, manifest-fix-needed

#1119 Shipwright: Add Ship of Harkinian
  bucket/shipwright.json
Labels: new package, review-needed
