Repository Calinou/scoop-games, pull requests merged in 2024-07, with the labels that each got.

#1174 Add: OpenTyrian2000
  bucket/opentyrian2000.json
Labels: new package, review-needed

#1177 Dolphin: fix bin and shortcut to executable due to change in the archive structure
  bucket/dolphin.json
Labels: bug, review-needed

#1179 daggerfallunity: Add version 1.1.1
  bucket/daggerfallunity.json
Labels: new package, review-needed

#1180 daggerfallunity: persist mods and gamefiles
  bucket/daggerfallunity.json
Labels: bug, review-needed

#1175 OpenTyrian2000: game data and persistence
  bucket/opentyrian2000.json
Labels: bug, enhancement, review-needed

#1184 Update settings.json: add pre/post_uninstall fields to sortJSON lists
  .vscode/settings.json
  bucket/zandronum.json
Labels: bug

#1187 Fix broken Marathon Shortcuts
  bucket/alephone-marathon-trilogy.json
Labels: bug, review-needed

#1188 battlenet: Add shortcut
  bucket/battlenet.json
Labels: bug, review-needed

#1190 warzone2100@4.5.0: offer all architectures
  bucket/warzone2100.json
Labels: enhancement, review-needed

#1173 sudachi: Fix an unpaired bracket in pre_install
  bucket/sudachi.json
Labels: review-needed

#1191 cnc-ddraw@6.7.0.0: Fix hash
  bucket/cnc-ddraw.json
Labels: bug, review-needed

#1192 xonotic: Update to version 0.8.6, skip extract_dir, and fix autoupdate
  bucket/xonotic.json
Labels: bug, package update, review-needed

#1195 resolute: Add version 0.8.3
  bucket/resolute.json
Labels: new package, review-needed

#1197 RimSort: add 1.0.9
  bucket/rimsort.json
Labels: new package, manifest-fix-needed
