Repository Calinou/scoop-games, pull requests merged in 2024-08, with the labels that each got.

#1199 Add Stonecutter v1.0.0
  bucket/stonecutter.json
Labels: new package, review-needed

#1200 Update trenchbroom.json vcredist2015 dependency
  bucket/trenchbroom.json
Labels: bug, review-needed

#1154 gzdoom: Update to version 4.12.2 and fix URL
  bucket/gzdoom.json
Labels: review-needed

#1115 Add Pangea Software Ported Games
  bucket/billy-frontier.json
  bucket/bugdom-2.json
  bucket/bugdom.json
  bucket/cro-mag-rally.json
  bucket/mighty-mike.json
  bucket/nanosaur-2.json
  bucket/nanosaur.json
  bucket/otto-matic.json
Labels: new package, review-needed

#1092 Add playit version 0.15.12
  bucket/playit.json
Labels: new package

#1205 chunker-cli: Add version 1.0.0
  bucket/chunker-cli.json
Labels: new package, review-needed

#1204 chunker: Add version 1.0.0
  bucket/chunker.json
Labels: new package, review-needed

#1208 dolphin: Various fixes, including fixing portability
  bucket/dolphin-beta.json
  bucket/dolphin-dev.json
  bucket/dolphin.json
Labels: bug, review-needed

#1206 bedrock-launcher: Add version 2024.8.18.21
  bucket/bedrock-launcher.json
Labels: review-needed

#1214 sudachi: Fix homepage, url and autoupdate
  bucket/sudachi.json
Labels: bug, review-needed
