Repository Calinou/scoop-games, pull requests merged in 2024-12, with the labels that each got.

#1276 Update Ryujinx with active Fork
  bucket/ryujinx.json
Labels: package update, review-needed

#1275 steam-art-manager: Fix autoupdate URL
  bucket/steam-art-manager.json
Labels: bug, manifest-fix-needed

#1253 Create shadps4.json
  bucket/shadps4.json
Labels: new package, manifest-fix-needed

#1281 Fix openrct2 autoupdate url
  bucket/openrct2.json
Labels: bug, package update, review-needed

#1279 Update cemu-dev to use latest pre-release
  bucket/cemu-dev.json
Labels: package update, review-needed

#1280 Fix broken autoupdate url for Raze
  bucket/raze.json
Labels: bug, package update, manifest-fix-needed

#1283 duckstation-preview: fix shortcut issue, update bios link
  bucket/duckstation-preview.json
  bucket/duckstation.json
Labels: bug, review-needed

#1282 pcsx2, pcsx2-dev: fix autoupdate and persist
  bucket/pcsx2-dev.json
  bucket/pcsx2.json
Labels: bug, manifest-fix-needed

#1285 Tf2classic: Add version 2023-05-27
  bucket/tf2classic.json
Labels: manifest-fix-needed

#1286 shadps4-dev: Add new manifest
  bucket/shadps4-dev.json
Labels: new package, review-needed

#1292 epic-games-launcher: Use `head` & properly parse query params
  bucket/epic-games-launcher.json
Labels: bug, review-needed

#1294 chiaki-ng: Update and rename chiaki4deck.json manifest to chiaki-ng.json
  bucket/chiaki-ng.json
  bucket/chiaki4deck.json
Labels: enhancement, review-needed

#1298 Ryujinx@1.2.76: fix version string in autoupdate url and update
  bucket/ryujinx.json
Labels: bug, package update, review-needed

#1297 melonds: fix autoupdate URL, update to 1.0rc
  bucket/melonds.json
Labels: bug, package update, review-needed

#1300 gzdoom@4.14.0: Fixed gzdoom download url and hash
  bucket/gzdoom.json
Labels: bug, manifest-fix-needed

#1303 scummvm: rename if there's version in file name
  bucket/scummvm.json
Labels: bug, review-needed
