Repository Calinou/scoop-games, pull requests merged in 2024-06, with the labels that each got.

#1152 Add Bedrock Updater.
  bucket/bedrockupdater.json
Labels: new package, review-needed

#1081 undertale-mod-tool: remove extract dir as there is no longer a subfolder
  bucket/undertale-mod-tool.json
Labels: bug, review-needed

#1163 collapse-launcher: Add version 1.73.8
  bucket/collapse-launcher.json
Labels: new package, review-needed

#1158 Lime3DS: Add version 2114.1
  bucket/lime3ds.json
Labels: new package, review-needed

#1159 project64: Fix URL
  bucket/project64.json
Labels: bug, review-needed

#1157 mudlet: Fix URL
  bucket/mudlet.json
Labels: bug, review-needed

#1156 ppsspp-dev: Add ARM64, fix checkver, autoupdate, remove extract_dir
  bucket/ppsspp-dev.json
Labels: bug, enhancement, review-needed

#1155 steam-achievement-manager-syntaxtm: autoupdate fix for 0.6.0, name change
  bucket/steam-achievement-manager-syntaxtm.json
Labels: bug, review-needed

#1160 wii-backup-manager: Add version 0.4.6
  bucket/wii-backup-manager.json
Labels: new package, review-needed

#1161 modboy: Add version 3.11
  bucket/modboy.json
Labels: new package, review-needed

#1165 Add Dungeons Updater.
  bucket/dungeonsupdater.json
Labels: new package, review-needed

#1169 Add SimulationCraft to scoop-games
  bucket/simulationcraft.json
Labels: new package, review-needed

#1172 lim3ds@2115: Fix extract_dir and add it to autoupdate
  bucket/lime3ds.json
Labels: bug, review-needed

#1171 Change Prismlauncher persist files to symlink
  bucket/prismlauncher.json
Labels: bug, manifest-fix-needed
