Repository Calinou/scoop-games, pull requests merged in 2024-11, with the labels that each got.

#1264 Openfortress: Add version 21
  bucket/openfortress.json
Labels: new package, manifest-fix-needed

#1266 Update tf2-hud-editor.json
  bucket/tf2-hud-editor.json
Labels: package update, review-needed

#1270 Update Steam Art Manager to version 3.10.5
  bucket/steam-art-manager.json
Labels: package update, review-needed

#1272 Change shortcut creation path to reflect updated format
  bucket/steam-art-manager.json
Labels: bug, review-needed

#1274 lime3ds@2119.1: Update URLs to point to archive
  bucket/lime3ds.json
Labels: bug, review-needed
