Repository Calinou/scoop-games, pull requests merged in 2024-09, with the labels that each got.

#1217 Flashpoint: Add version 13
  bucket/flashpoint.json
Labels: review-needed

#1218 hedge-mod-manager: Add version 7.12-9
  bucket/hedge-mod-manager.json
Labels: review-needed

#1220 MegaAntiCheat: Add version v0.1.0
  bucket/megaanticheat.json
Labels: manifest-fix-needed

#1223 megaanticheat: fix notes part
  bucket/megaanticheat.json
Labels: bug, manifest-fix-needed

#1224 Mcrcon: Repair manifest
  bucket/mcrcon.json
Labels: bug, review-needed

#1226 Fix chunker and chunker-cli
  bucket/chunker-cli.json
  bucket/chunker.json
Labels: bug, package update, review-needed

#1227 lime3ds: fix bin and shortcuts
  bucket/lime3ds.json
Labels: review-needed

#1230 Update pcsx2.json and pscsx2-dev.json
  bucket/pcsx2-dev.json
  bucket/pcsx2.json
Labels: bug, package update, manifest-fix-needed

#1229 Fix OSU extract_dir
  bucket/osulazer.json
Labels: bug, review-needed
