Repository Calinou/scoop-games, pull requests merged in 2024-10, with the labels that each got.

#1238 Update sudachi.json with GitHub releases
  bucket/sudachi.json
Labels: bug, review-needed

#1245 fmodel: Add version 4.4.3.6
  bucket/fmodel.json
Labels: new package, review-needed

#913 shatteredpixeldungeon: add version 2.0.2
  bucket/shatteredpixeldungeon.json
Labels: new package, review-needed

#936 rvgl: add hash checking and persists
  bucket/rvgl.json
Labels: enhancement, review-needed

#1255 supermodel: add version 0.3a-git-f9cb795
  bucket/supermodel.json
Labels: new package, review-needed
