Repository Calinou/scoop-games, pull requests merged in 2024-04, with the labels that each got.

#1122 dreamm: Add version 2.1.2
  bucket/dreamm.json
Labels: new package, review-needed

#1120 ff-logs-uploader: Add initial version 8.3.20
  bucket/ff-logs-uploader.json
Labels: new package, review-needed

#1123 assetstudio: Redirect to successor fork
  bucket/assetstudio.json
Labels: new package, review-needed

#1126 Use VC build of chiaki4deck due to upstream issues
  bucket/chiaki4deck.json
Labels: bug, review-needed

#1124 scummvm: fix shortcut creation
  bucket/scummvm.json
Labels: bug, review-needed

#1127 fix: rename dl_with_cache to Invoke-CachedDownload
  bucket/blade-of-agony.json
  bucket/freedoom.json
  bucket/speed-dreams.json
Labels: bug, manifest-fix-needed

#1128 freedoom: fix creating shortcut
  bucket/freedoom.json
Labels: bug, review-needed

#1130 Change dwarf fortress autoupdate url to use $underscoreVersion
  bucket/dwarf-fortress.json
Labels: bug, package update, review-needed

#1131 tic-80: add shim
  bucket/tic-80.json
Labels: enhancement, review-needed

#1139 Tmaze: file names changed
  bucket/tmaze.json
Labels: bug, review-needed

#1137 dwarf-fortress@50.12 fix persist folders
  bucket/dwarf-fortress.json
Labels: bug, review-needed

#1143 demulshooter@12.2: Fix hash
  bucket/demulshooter.json
Labels: bug, review-needed

#1135 battlenet: Refactor
  bucket/battlenet.json
Labels: enhancement, review-needed

#1144 battlenet: Fix pre_install
  bucket/battlenet.json
Labels: bug, review-needed
