Repository Calinou/scoop-games, pull requests merged in 2025-03, with the labels that each got.

#1335 Add PATH support for Stonecutter.
  bucket/stonecutter.json
Labels: enhancement, review-needed

#1332 xxmi: Add version 1.5.0
  bucket/xxmi.json
Labels: new package

#1336 Remove PATH support for Stonecutter.
  bucket/stonecutter.json
Labels: enhancement, review-needed

#1334 mudlet: Update to 4.19.1 and fix download url, autoupdate and add 32/64-bit split
  bucket/mudlet.json
Labels: package update, review-needed
