Repository Calinou/scoop-games, pull requests merged in 2025-02, with the labels that each got.

#1320 0ad: Update to version 0.27.0
  bucket/0ad.json
Labels: package update, review-needed

#1322 fix: shadps4 checkver
  bucket/shadps4.json
Labels: bug, package update, review-needed

#1325 Flashpoint: repair extraction and shortcut
  bucket/flashpoint.json
Labels: bug, review-needed

#1328 Fix BZFlag 2.4.28 hash and switch the vcredist
  bucket/bzflag.json
Labels: bug
