Repository Calinou/scoop-games, pull requests merged in 2025-06, with the labels that each got.

#1429 Fix manifests
  bucket/infraarcana.json
  bucket/lime3ds.json
  bucket/openmw-nightly.json
  bucket/rpcs3.json
  bucket/ryujinx-canary.json
  bucket/tf2classic.json
Labels: bug, package update, manifest-fix-needed

#1424 Fishstrap: add version 2.9.1.2
  bucket/fishstrap.json
Labels: new package, review-needed

#1439 melonds: fix incorrect persistence logic
  bucket/melonds.json
Labels: bug, review-needed

#1443 ryujinx(-canary): Update URLs, drop arm64 support
  bucket/ryujinx-canary.json
  bucket/ryujinx.json
Labels: bug, package update, review-needed

#1446 shadps4-dev: Update to version 2025-06-06-91d2945, fix checkver
  bucket/shadps4-dev.json
Labels: bug, package update, review-needed

#1448 (chore): Replace vcredist2015-2019 with vcredist2022
  bucket/dolphin.json
  bucket/extremetuxracer.json
  bucket/vkquake.json
  bucket/vkquake2.json
Labels: bug, enhancement, review-needed

#1450 unciv: Fix checkver
  bucket/unciv.json
Labels: bug, review-needed

#1449 zelda64recomp: Add version 1.2.0
  bucket/zelda64recomp.json
Labels: new package, review-needed

#1447 sm64coopdx: Add version 1.3.2
  bucket/sm64coopdx.json
Labels: new package, review-needed

#1452 rpcs3@0.0.37-18025: Update url, fix checkver, fix autoupdate
  bucket/rpcs3.json
Labels: bug, review-needed

#1459 vkquake: Update to version 1.32.3.1, fix autoupdate
  bucket/vkquake.json
Labels: bug, package update, review-needed

#1463 modboy@3.11: Fix checkver, fix autoupdate
  bucket/modboy.json
Labels: review-needed
