Repository Calinou/scoop-games, pull requests merged in 2025-04, with the labels that each got.

#1349 Add doukutsu-rs
  bucket/doukutsu-rs.json
Labels: new package, review-needed

#1331 Patch raze to use hotfix zip.
  bucket/raze.json
Labels: bug, package update, manifest-fix-needed

#1291 shadps4-dev: fix autoupdate url
  bucket/shadps4-dev.json
Labels: bug, review-needed

#1354 Fix removal of .exe file in sameboy package
  bucket/sameboy.json
Labels: bug, review-needed

#1359 goggalaxy: Fix autoupdate
  bucket/goggalaxy.json
Labels: bug, review-needed

#1360 Create azahar.json
  bucket/azahar.json
Labels: new package, review-needed

#1362 Create reloaded-ii.json
  bucket/reloaded-ii.json
Labels: new package, review-needed

#1363 xenia-canary: Fix autoupdate & xenia: slight update to manifest description
  bucket/xenia-canary.json
  bucket/xenia.json
Labels: bug, package update, review-needed

#1364 Prismlauncher: Correctly persist config files for non-admins
  bucket/prismlauncher.json
Labels: bug, review-needed

#1369 azahar@2120.2: Licence fix & reloaded-ii@1.28.8: Licence fix
  bucket/azahar.json
  bucket/reloaded-ii.json
Labels: bug, review-needed

#1368 duckstation: Fix licence and add arm64 build
  bucket/duckstation-preview.json
  bucket/duckstation.json
Labels: bug, enhancement, review-needed

#1372 prismlauncher: Persist skins folder
  bucket/prismlauncher.json
Labels: bug, review-needed

#1377 xenia-canary: Fix persists
  bucket/xenia-canary.json
Labels: bug, review-needed

#1379 r2modman: Add pre_install script to extract app
  bucket/r2modman.json
Labels: bug, review-needed

#1380 maa: Add version 5.15.2
  bucket/maa.json
Labels: new package, manifest-fix-needed

#1384 dolphin: update to version 2503a
  bucket/dolphin.json
Labels: bug, package update, review-needed

#1382 ryujinx: fix checkver
  bucket/ryujinx-canary.json
  bucket/ryujinx.json
Labels: bug, package update, manifest-fix-needed

#1383 undertale-mod-tool@0.8.0.0: Update version
  bucket/undertale-mod-tool.json
Labels: bug, package update, manifest-fix-needed

#1385 epic-games-launcher: Fix post_install & pre_uninstall script
  bucket/epic-games-launcher.json
Labels: bug, review-needed

#1386 playit: Update to version 0.15.26
  bucket/playit.json
Labels: bug, package update, review-needed
