Repository Calinou/scoop-games, pull requests merged in 2025-08, with the labels that each got.

#1492 asset-ripper@1.3.2: Remove post_uninstall script, add persist
  bucket/asset-ripper.json
Labels: bug, review-needed

#1491 evemaptool@1.41: Update repack url
  bucket/evemaptool.json
Labels: bug, manifest-fix-needed

#1500 retro-rogue-collection: Add version 3.1.0
  bucket/retro-rogue-collection.json
Labels: new package, review-needed
