Repository Calinou/scoop-games, pull requests merged in 2025-07, with the labels that each got.

#1467 rgbds: Update to version 0.9.3, fix autoupdate
  bucket/rgbds.json
Labels: bug, package update, review-needed

#1469 Mesen@2.1.1: Update to mesen2
  bucket/mesen.json
Labels: package update, review-needed

#1474 naev: Fix shortcut issue
  bucket/naev.json
Labels: bug, review-needed

#1475 taisei: Update to version 1.4.3, remove 32-bit arch, add hash extraction
  bucket/taisei.json
Labels: bug, enhancement, package update, review-needed

#1476 osulazer: Update to version 2025.710.0-lazer, fix checkver
  bucket/osulazer.json
Labels: bug, package update, review-needed

#1477 goggalaxy: Persist galaxy-2.0.db to avoid rescanning, remove hash extraction
  bucket/goggalaxy.json
Labels: bug, review-needed

#1479 playit: Update to version 0.16.2, simplify pre_install script, fix autoupdate
  bucket/playit.json
Labels: bug, package update, review-needed

#1483 snes9x-dev: Update to version 1.63-1503, fix checkver
  bucket/snes9x-dev.json
Labels: bug, package update, review-needed
