Repository Calinou/scoop-games, pull requests merged in 2025-01, with the labels that each got.

#1302 uabea: Add version 8
  bucket/uabea.json
Labels: new package, review-needed

#1241 ryujinx-ava: Remove as version is superseeded by mainline ryujinx
  bucket/ryujinx-ava.json
Labels: package update, manifest-fix-needed

#1304 fix cxbx-reloaded
  bucket/cxbx-reloaded.json
  bucket/ppsspp-dev.json
Labels: bug, package update, review-needed

#1306 retroarch-nightly: add and fixes persistent folders
  bucket/retroarch-nightly.json
Labels: bug, review-needed

#1307 xemu: Update xemu.json with arm64 build & portable mode enablement
  bucket/xemu.json
Labels: enhancement, review-needed

#1308 Update rare.json
  bucket/rare.json
Labels: bug, package update, review-needed

#1312 xemu: Fix post_install script overwriting config file even when not empty
  bucket/xemu.json
Labels: bug, review-needed

#1311 Create pathofbuilding-poe2-community.json
  bucket/pathofbuilding-poe2-community.json
Labels: new package, review-needed

#1313 sokoban: update license to Apache-2.0
  bucket/sokoban.json
Labels: enhancement, review-needed

#1316 mesa3d & mesa3d-mingw: Add version 24.3.3
  bucket/mesa3d-mingw.json
  bucket/mesa3d.json
Labels: new package, manifest-fix-needed

#1318 Tf2classic: repair checkver
  bucket/tf2classic.json
Labels: bug, manifest-fix-needed
