Repository Calinou/scoop-games, pull requests merged in 2025-05, with the labels that each got.

#1390 runelite: Add arm64 arch & fix installation failure (#1232)
  bucket/runelite.json
Labels: bug, enhancement, review-needed

#1392 playback: add version 1.7.0
  bucket/playback.json
Labels: new package, review-needed

#1393 asset-ripper: Add version 1.2.2
  bucket/asset-ripper.json
Labels: new package, review-needed

#1389 sak: Add version 0.7.14
  bucket/sak.json
Labels: new package, review-needed

#1395 project64-dev: Fix installation failure
  bucket/project64-dev.json
Labels: bug, review-needed

#1396 undertale-mod-tool: Fix installation
  bucket/undertale-mod-tool.json
Labels: bug, review-needed

#1398 feat: add gdsdecomp
  bucket/gdsdecomp.json
Labels: new package, review-needed

#1400 assetstudio: add suggest
  bucket/assetstudio.json
Labels: bug, review-needed

#1401 maa@5.16.3: resolve conflicts with maa-cli
  bucket/maa.json
Labels: bug, manifest-fix-needed

#1399 ryujinx: Add arm64 arch & suggest
  bucket/ryujinx-canary.json
  bucket/ryujinx.json
Labels: enhancement, review-needed

#1402 sak: update notes
  bucket/sak.json
Labels: bug, review-needed

#1404 chiaki-ng: Add arm64 build, switch x64 to MSYS2 build
  bucket/chiaki-ng.json
Labels: enhancement, review-needed

#1411 cambridge@0.3.4: Fix urls, fix hash
  bucket/cambridge.json
Labels: bug, review-needed

#1413 endless-sky: Update to version 0.10.12, remove 32bit arch, fix autoupdate
  bucket/endless-sky.json
Labels: bug, package update, review-needed

#1415 doomrunner: Update to version 1.9.1, fix autoupdate
  bucket/doomrunner.json
Labels: bug, package update, review-needed

#1416 katrain: Update to version 1.16, fix autoupdate
  bucket/katrain.json
Labels: bug, package update, review-needed

#1417 angband-dev: Update to version 4.2.5-389-g1b3978f8d, fix checkver
  bucket/angband-dev.json
Labels: bug, package update, review-needed

#1419 dolphin-dev: Update to version 2503a-603, fix checkver
  bucket/dolphin-dev.json
Labels: bug, enhancement, package update, review-needed

#1422 dwarf-fortress-lnp@0.47.05-r11: Fix urls
  bucket/dwarf-fortress-lnp.json
Labels: bug, review-needed

#1425 megamek(-dev), megameklab(-dev), megahq(-dev): Update to version 0.50.06, fix checkver, fix autoupdate, add hash, add extract_dir
  bucket/megamek-dev.json
  bucket/megamek.json
  bucket/megameklab-dev.json
  bucket/megameklab.json
  bucket/mekhq-dev.json
  bucket/mekhq.json
Labels: bug, package update, review-needed

#1423 endless-sky@0.10.12: Fix shortcuts, remove bin
  bucket/endless-sky.json
Labels: bug, review-needed

#1427 Fix manifests
  bucket/extremetuxracer.json
  bucket/gdsdecomp.json
  bucket/infraarcana.json
  bucket/lambdahack.json
  bucket/lzdoom.json
  bucket/mameui.json
  bucket/openmsx-dev.json
  bucket/prboom-plus.json
  bucket/prismlauncher-qt5.json
  bucket/rbdoom-3-bfg.json
  bucket/rimpy-pre-release.json
  bucket/rimpy.json
  bucket/rvgl-launcher.json
  bucket/stella.json
  bucket/tf2classic.json
  bucket/tome4.json
  bucket/trenchbroom.json
  bucket/umod.json
  bucket/yquake2.json
Labels: bug, package update, review-needed
